### ISSUE TITLE
I2C stops working and locks when wrong address is provided

### ISSUE THREAD

**Issue by acastellane** [OpenCAPI/omi_host_fire#2]
Hi,
for example when accessing a FIRE's FML register higher than 15 (only 8 are available in the design), we get an I2C lock. A reset of FIRE is required.

**Comment by bmesnet** [comment]
Corrected in pull request #3

**Comment by acastellane** [comment]
Thanks for mods.
New errors codes can be checked at : https://opencapi.github.io/omi-doc/blocs/enablement_details/ or in the enablement python code :
https://github.com/OpenCAPI/omi_enablement/blob/main/python/fire.py
Best regards
